### ISSUE TITLE
Document better that Log Analytics must use a  token_auth with admin permission or super user 

### ISSUE THREAD

**Issue by tillsteinbach** [matomo-org/matomo-log-analytics#141]
I have a setup with an apache running piwik and a second apache running the piwik-log-analytics script in piped mode. I can see the logs in pewik, but for all requests the IP is the IP of the machine the piwik-log-analytics script runs on. Not the IP of the actual request.

Is this a bug, or am I missing an option for this use case?

**Comment by sgiehl** [comment]
The log files you are importing have the correct IPs within the entries? Those IPs should be used for importing if available. Maybe the importer can't read the format. What exactly is the output of log importer?

**Comment by tillsteinbach** [comment]
I'm not importing log files. I use the piped mode like this:
`import_logs.py --url=https://myinstallation.de/piwik/ --token-auth=mysecret --idsite=4 --recorders=1 --log-format-name=common_complete --add-sites-new-hosts --recorder-max-payload-size=1 --enable-http-errors --enable-http-redirects --enable-static --enable-bots --enable-reverse-dns -`

The entries look like that:
`urlofmyvhost:443 1.2.3.4 - - [04/Jun/2016:15:28:07 +0200] "GET /url HTTP/1.1" 200 15384 "http://other.url" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5"`

**Comment by tillsteinbach** [comment]
Doooooo! I got it!
I looked through the piwik code and found that the way the IP is written depends on the rights the user has. The user I took the auth-token from only had view permission on this particular website. So the script was able to write logs, but the IP was actually taken from the request when the record was forwarded and not from the attribute itself!

This should definitely go into the README!

**Comment by mattab** [comment]
Thanks for letting us know @tillsteinbach  - fixed in https://github.com/piwik/piwik-log-analytics/commit/ca215c2b850c5429f6a62b96777b5f0367065062

**Comment by kwisatz** [comment]
Just wanted to highlight that while the README has a mention of this, the HowTo does not, which caused me to also go digging into the code as @tillsteinbach did back in 2016.

See 
- https://matomo.org/docs/log-analytics-tool-how-to/
- https://forum.matomo.org/t/import-log-analytics-no-datas-shown/36226/

The only part that is still confusing here, @mattab, is the title `Log Analytics and piwik on different machines`. In my case, the machine is the same, but logs are older than 1 day which makes the `token_auth` equally mandatory.

**Comment by mattab** [comment]
Thanks @kwisatz for catching this issue in the doc! :+1: 
Added mention of token-auth in https://matomo.org/docs/log-analytics-tool-how-to/
