### ISSUE TITLE
IIS (6.0) imports fail

### ISSUE THREAD

**Issue by janhurst** [matomo-org/matomo-log-analytics#166]
Hi, 
I've beaten my head on this for a while now, but as best I can tell IIS 6.0 log format is not supported?
When I set the format as "iis" I run into various failures, the closest I get is eventually all log lines failing as invalid lines.

I've been digging through the python code, and it seems like there is nothing in the regexes code that handles comma delimited log lines (which IIS 6.0 logging format produces)

Can you clarify is IIS 6.0 log format is expected to work? Is the "iis" setting only support to work with W3C format IIS logs? (specifically time in milliseconds?)

(Note my log files, to make things worse, don't have any headers (daily roll overs))

**Comment by janhurst** [comment]
After further experimentation (and lack of any comments here :)), I've gone ahead and hacked a IIS 6 compatible format. When I can get my head around how the unit testing is being done and actually write some unit tests I'll try and put a PR together.

**Comment by mattab** [comment]
@janhurst we would love to see your pull request and improving IIS 6 log format import. Do you need any help with creating the PR?

**Comment by mattab** [comment]
Please can you post an example log file from IIS 6 that didn't import properly?
