### ISSUE TITLE
Exception in thread Thread-1: Traceback (most recent call last):

### ISSUE THREAD

**Issue by Umairbadar4** [matomo-org/matomo-log-analytics#203]
File "C:\Python\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Python\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python\lib\pyrebase\pyrebase.py", line 556, in start_stream
    self.sse = ClosableSSEClient(self.url, session=self.make_session(), build_headers=self.build_headers)
  File "C:\Python\lib\pyrebase\pyrebase.py", line 518, in __init__
    super(ClosableSSEClient, self).__init__(*args, **kwargs)
  File "C:\Python\lib\sseclient.py", line 28, in __init__
    self._connect()
  File "C:\Python\lib\pyrebase\pyrebase.py", line 522, in _connect
    super(ClosableSSEClient, self)._connect()
  File "C:\Python\lib\sseclient.py", line 34, in _connect
    **self.requests_kwargs)
  File "C:\Python\lib\requests\api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python\lib\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'prefetch'

**Comment by Umairbadar4** [comment]
Im trying to send IoT Push Notification to Android using Firebase Cloud Messaging.

`from pyfcm import FCMNotification
import pyrebase

push_service = FCMNotification(api_key="")

config = {
    "apiKey": "",
    "authDomain": "",
    "databaseURL": "",
    "projectId": "",
    "storageBucket": "",
    "messagingSenderId": ""
  };

firebase = pyrebase.initialize_app(config)
db = firebase.database()

message_title = "Fire Alert"
message_body = db.child("address").get().val()
message_body = "Fire Breakeage at:"+ str(message_body)
registration_id = db.child("message").get().val()

def stream_handler(post):
	print(post)
	if (post['data'] is 1):
		result = push_service.notify_single_device(registration_id=registration_id, message_title=message_title, message_body=message_body)
		print(result)
my_stream = db.child("fire_sensor_status").stream(stream_handler, None)
`

**Comment by sgiehl** [comment]
And what exactly is your problem with the Matomo LogAnalyizer ?

**Comment by Umairbadar4** [comment]
@sgiehl Actually Im new to this forum that is why by mistake i have put my issue under this. Sorry about that.

**Comment by sgiehl** [comment]
Actually this is no forum. If you have a question that does not directly belong to a specific project that is here on github, it might maybe make more sense to ask you question on stackoverflow or similar.
