### ISSUE TITLE
How to populate Pages tab with log analytics ?

### ISSUE THREAD

**Issue by gaby44541** [matomo-org/matomo-log-analytics#233]
Hello,
I use custom log with custom regex.
How to populate Pages tab with log analytics ? 
Actually when I import logs into Piwik, the user agent and custom variables are properly imported but  none pages.
Here how i launch the script with custom regex :

python misc/log-analytics/import_logs.py --url=http://web --idsite=1 --debug --debug --log-format-regex="(?P<date>\S*)\s+(?P<level>\S*)\s+(?P<path>\S*) - \[(?P<user_agent>[^\]]*)\] \[(?P<client_os>[^\]]*)\] \[(?P<client_browser>[^\]]*?)\] \[(?P<ip>[^\]]*)\] \[(?P<query_string>[^\]]*?)\] \[(?P<referrer>[^\]]*?)\] \[(?P<status>[^\]]*?)\] \[(?P<action_name>[^\]]*?)\] {cvar=\[(?P<regroupement>[^\]]*?)\] \[(?P<profil>[^\]]*?)\] \[(?P<niveauEleve>[^\]]*?)\] \[(?P<idSession>[^\]]*?)\] \[(?P<etablissement>[^\]]*?)\] \[(?P<fonction>[^\]]*?)\] \[(?P<espace>[^\]]*?)\] \[(?P<parcoursFiche>[^\]]*?)\] \[(?P<typeFiche>[^\]]*?)\] \[(?P<action>[^\]]*?)\]} - (?P<message>.*)" --regex-group-to-visit-cvar="status=status" --regex-group-to-visit-cvar="profil=profil" --regex-group-to-page-cvar="regroupement=regroupement" --log-date-format='%d/%m/%Y_%H:%M:%S.%f' stats3.log 

Is there a keyword for url page and title page ?
Thanks a lot !

**Comment by mackuba** [comment]
Page titles don't work with log analytics because logs only include URLs, but the "Pages" report (first in "Behavior") should work and you should see URLs there, what do you see there? How do your log lines look like?

**Comment by gaby44541** [comment]
For page title, i tried to add 'action_name':'test' in args tab (line 1880 ~ according to the version). And it works. I would like now to use the var action_name in the regex. Do you know what can i add in the script python to use a new var ?

For page url,  the log looks like :
`23/11/2018_07:32:26.574 INFO  f.o.folios.web.statistiques.LogStats - [Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0] [Unix] [Firefox-63.0] [127.0.0.1] [http://folios:8080/webfolio/gestion_classes/recherche_classe.jsp?PROC=RECHERCHE_CLASSE&ACTION=PREPARER_RECHERCHE&CODE_ETABLISSEMENT=00200001] [http://folios:8080/servlet/com.jsbsoft.jtf.core.SG?PROC=GESTION_ACADEMIE] [200] [Folios - Gestion des classes] {cvar=[ac-demo] [ADMINISTRATEUR_ACADEMIQUE] [] [] [] [] [] [] [] []} - Folios - Gestion des classes`

And the regex : 
`(?P<date>\S*)\s+(?P<level>\S*)\s+(?P<path>\S*) - \[(?P<user_agent>[^\]]*)\] \[(?P<client_os>[^\]]*)\] \[(?P<client_browser>[^\]]*?)\] \[(?P<ip>[^\]]*)\] \[(?P<query_string>[^\]]*?)\] \[(?P<referrer>[^\]]*?)\] \[(?P<status>[^\]]*?)\] \[(?P<action_name>[^\]]*?)\] {cvar=\[(?P<regroupement>[^\]]*?)\] \[(?P<profil>[^\]]*?)\] \[(?P<niveauEleve>[^\]]*?)\] \[(?P<idSession>[^\]]*?)\] \[(?P<etablissement>[^\]]*?)\] \[(?P<fonction>[^\]]*?)\] \[(?P<espace>[^\]]*?)\] \[(?P<parcoursFiche>[^\]]*?)\] \[(?P<typeFiche>[^\]]*?)\] \[(?P<action>[^\]]*?)\]} - (?P<message>.*)`

After the ip, i catch the group name "query_string" (for the page url, is it ok ? is there another group name for url ?) and referrer

**Comment by mackuba** [comment]
You're right, looks like there is no support currently for extracting the `action_name` matched by the regex even if you do specify it in the regex. Sounds like what you've changed is more or less the right approach.

As for the URL, it seems that all standard regexes specify a `path` segment which is just the path after the hostname (starting e.g. from `/webfolio` in your case). The full URL is constructed from that path. So you'd have to either specify the regex so that the path element starts after the hostname, or somehow hack the code to take the full URL and process it differently.

I think the `query_string` is supposed to be only the part after the `?`, I don't know what the code will do if you pass the full URL in that place and no `path` element...
