### ISSUE TITLE
Lack of Python3 support is a serious issue

### ISSUE THREAD

**Issue by udf2457** [matomo-org/matomo-log-analytics#257]
https://github.com/python/devguide/pull/344
https://www.python.org/dev/peps/pep-0373/#possible-features-for-2-7

As per the above links, Python2, is now fully dead, as per a quote from the above:

> no updates, not even source-only security patches, after that date

Issues #3 & #242 seem to be an eternal work-in-progress.

This really needs to be prioritised as a major issue that needs addressing !

P.S. Don't ask me to contribute code, I can't code in Python, at all, not even at newbie level.  I am just a Matomo user that doesn't want to be forced to drop Matomo due to reliance on obsolete, unsupported version of Python.

**Comment by Findus23** [comment]
I am fully aware of the end of life of Python2, but #242 isn't a work-in-progress. It is mostly finished but depends on more people testing it. 
There are about 60 options that can be combined for all kinds of rare use cases and I don't have the ability to test if all of them still work as before.

**Comment by udf2457** [comment]
Afraid I only use `--url --auth-user --auth-password --enable-http-errors --enable-http-redirects --enable-static --enable-bots --recorders --log-format-name=nginx_json`

Maybe you can release two versions ? Simplified one for those of us who just want a simple life (quick and easy integration with NGINX) and an advanced one (which is initially released with a big fat disclaimer at the top saying "60 currently untested monsters lurk within")

**Comment by mattab** [comment]
we won't release two versions @udf2457 - but be great if you already help test https://github.com/matomo-org/matomo-log-analytics/pull/242 and leave your comment/update there :ok_hand:

**Comment by udf2457** [comment]
Are we anywhere nearer getting rid of Python 2 once and for all ?  I'm on the verge of giving up and dumping Matomo for an alternative log analysis tool.

At the present time, Matomo is the only piece of code in our entire infrastrucure that still uses Python 2.  We see no reason to continue "supporting" such obsolescene throuh un-necessary installation of Python 2.

**Comment by Findus23** [comment]
@udf2457 The python3 support is already "finished" since last year in #242. Did you already test if it works correctly in your environment? If enough people report back, it should be fine to release it together with Matomo 4 this year.

You can get the python script from that branch here: https://github.com/Findus23/piwik-log-analytics/blob/python3-2019/import_logs.py

**Comment by udf2457** [comment]
Its not finished if it's not tested.  

I suggested earlier this year that if testing is a problem, you should release a simplified version that didn't require god knows hows how many combinations of testing to test for all 60 flags or whatever stupidity of number of options flags are in the full version.

I'm leaving the Matomo community and going elsewhere.

**Comment by sgiehl** [comment]
I would suggest to drop the support for Python 2 with release of Matomo 4. That means we could maybe already merge the changes of #242 into 4.x-dev branch and check if at least all Matomo tests are running correctly with Python 3 on travis.

@mattab is python 3 support considered as part of Matomo 4 or should that be available for Matomo 3 as well?

**Comment by Findus23** [comment]
> Its not finished if it's not tested.

Correct. I'd therefore propose to also announce a beta release together with the first Matomo 4 beta release.

**Comment by mattab** [comment]
> is python 3 support considered as part of Matomo 4 or should that be available for Matomo 3 as well?

I'm not too familiar with availability of Python 3 on older LTS systems, but in general it makes sense to drop support for python2 and only support one codebase at a time (python 3). So sounds good to me to proceed with beta testing the python3 version as part of Matomo 4 :+1:

**Comment by jreynder** [comment]
You can use a docker python 2 container (as I do). 
`docker run -it --rm --name import_logs -v /var/www/:/var/www/:ro -v /var/run/mysqld/:/run/mysqld/ -v /var/log/:/var/log/:ro python:2-alpine python /var/www/matomo/misc/log-analytics/import_logs.py --url=http://your.matomo.server/ --idsite=1 --recorders=4 --token-auth=your.token /var/log/nginx/your.access.log`

**Comment by sgiehl** [comment]
Python 3 support will be part of Matomo 4.
