### ISSUE TITLE
--url= set to use HTTP redirected on HTTPS makes importer fail

### ISSUE THREAD

**Issue by Berbe** [matomo-org/matomo-log-analytics#261]
Issue already found reported ages ago on an old tracker: https://issues.matomo.org/6699

- Matomo version `3.13.5`
- Corresponding `imports_logs.py` version b3973f3cd0cb773eb9cf3bfff439cc43640c5f15

Steps to reproduce:
1. `--url` set to use a HTTP URL
2. Matomo redirects to a HTTPS URL
3. Importer retries & eventually fails with the following error:
   ```
   [INFO] Error when connecting to Matomo: <urlopen error Matomo returned an invalid response: <!DOCTYPE html> [...]
   ```

**Comment by sgiehl** [comment]
Hi @Berbe. Thanks for creating the issue. The old issue actually still exist here. See #42. So closing this as duplicate. If you are familiar with python and have some time to implement the changes needed for it, we are always happy to review and merge pull request 😄
