### ISSUE TITLE
IP2Location plugin breaks log-import

### ISSUE THREAD

**Issue by sgoeting** [matomo-org/matomo-log-analytics#271]
With the plugin IP2Location active we get errors wich break the import.

ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] Error query: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'location_country' at row 1 In query: INSERT INTO piwik_log_visit (idvisitor, config_id, location_ip, idsite, visit_first_action_time, visit_goal_buyer, visit_goal_converted, visit_last_action_time, visitor_days_since_first, visitor_days_since_order, visitor_returning, visitor_count_visits, visit_entry_idaction_name, visit_entry_idaction_url, visit_exit_idaction_name, visit_exit_idaction_url, visit_total_actions, visit_total_interactions, visit_total_searches, referer_keyword, referer_name, referer_type, referer_url, location_browser_lang, config_browser_engine, config_browser_name, config_browser_version, config_device_brand, config_device_model, config_device_type, config_os, config_os_version, visit_total_events, visitor_localtime, visitor_days_since_last, config_resolution, config_cookie, config_director, config_flash, config_gears, config_java, config_pdf, config_quicktime, config_realplayer, config_silverlight, config_windowsmedia, visit_total_time, location_country, location_latitude, location_longitude, campaign_content, campaign_id, campaign_keyword, campaign_medium, campaign_name, campaign_source) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) Parameters: array (
.....
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 44 => 0,
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 45 => 0,
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 46 => 0,
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 47 => 'rabat-sale-kenitra',
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 48 => '-6.833',
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 49 => '0',
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 50 => NULL,
ERROR BulkTracking[2020-07-13 12:18:10 UTC] [f60be] 51 => NULL,
....)

Field 47 is the location_country-field. DB-definition is CHAR[3]
With the IP2Location plugin de-activated no errors like this are shown. But in that case we are missing the location_country etc.

Is there a workaround or something else that can solve this problem?

**Comment by sgiehl** [comment]
Guess that's a problem with the country code returned by the plugin maybe. As that plugin is developed by a third party, maybe try creating an issue in the plugin repo: https://github.com/ip2location/ip2location-piwik
