### ISSUE TITLE
When input is stdin ('-'), import_logs.py doesn't work

### ISSUE THREAD

**Issue by jjmerchante** [matomo-org/matomo-log-analytics#273]
With the latest changes (I think commit: https://github.com/matomo-org/matomo-log-analytics/commit/58e162ea9c10d3d2e4859e869ea586edf818eaa6) I am unable to import logs from syslog using the recommended way (https://github.com/matomo-org/matomo-log-analytics/tree/3.x-dev#matomosh-syslog-ng-version)

The input file for `ìmport_logs.py` is `-`, but I think it is removed in the following line: https://github.com/matomo-org/matomo-log-analytics/blob/3.x-dev/import_logs.py#L952 (`all_filenames = all_filenames + glob.glob(self.filename)`)

**Comment by curzon01** [comment]
that's corrent, can confirm issue after last matomo update to 3.14.0 - and it blocked one of my server with cpu load of 100% so web sites where down...

**Comment by sgiehl** [comment]
@jjmerchante @curzon01 could you check if those change would fix the issue: https://github.com/matomo-org/matomo-log-analytics/compare/3.x-dev...stdin

**Comment by jjmerchante** [comment]
With those changes, it works for me :+1:

**Comment by curzon01** [comment]
confirmed, fix works like before v3.14.0
