### ISSUE TITLE
Import *.gz files: UnboundLocalError: local variable 'file' referenced before assignment

### ISSUE THREAD

**Issue by Prinzhorn** [matomo-org/matomo-log-analytics#287]
From what I understand the script should automatically detect and unzip these? It doesn't like my `*.gz` Apache logs. Can be reproduced with an empty gzipped file (literally `gzip empty` with a 0 byte `empty` file).

```sh
python3 import_logs.py \
  --dry-run \
  --url='http://localhost:8080' \
  --token-auth=1234 \
  --idsite=1 \
  empty.gz
```

```
Parsing log empty.gz...
Traceback (most recent call last):
  File "import_logs.py", line 2674, in <module>
    main()
  File "import_logs.py", line 2640, in main
    parser.parse(filename)
  File "import_logs.py", line 2378, in parse
    data = file.read(100)
UnboundLocalError: local variable 'file' referenced before assignment
```

Edit: I also had to apply #281 before the script even ran

**Comment by Prinzhorn** [comment]
I think this needs to be outdented? https://github.com/matomo-org/matomo-log-analytics/blob/2299a422f960c1e94a1a7ae8e401a92c3c891d84/import_logs.py#L2355

Then you get 

```
Traceback (most recent call last):
  File "import_logs.py", line 2674, in <module>
    main()
  File "import_logs.py", line 2640, in main
    parser.parse(filename)
  File "import_logs.py", line 2359, in parse
    file = open_func(filename, mode='r', encoding=config.options.encoding, errors="surrogateescape")
  File "/usr/lib/python3.8/gzip.py", line 50, in open
    raise ValueError("Argument 'encoding' not supported in binary mode")
ValueError: Argument 'encoding' not supported in binary mode
```

But either way these are never used

```py
if filename.endswith('.bz2'):
    open_func = bz2.BZ2File
elif filename.endswith('.gz'):
    open_func = gzip.open
```

Edit: was originally outdented https://github.com/matomo-org/matomo-log-analytics/commit/3ed7fb3ecceea49ecdbc83e03226fe608c0ccedd#diff-d3ce55e4e69e2e5cf378d48ecdde2c307202281015e287647b8e6dfd633e84e9R944-R959

Edit: @sgiehl broke it https://github.com/matomo-org/matomo-log-analytics/commit/47cec277b2d90479b016d0c1ec3c68f56b3b1c34

Could a linter catch these in the future? I'm not familiar with Python tooling, in JavaScript I'd get "open_func is assigned but never used"

**Comment by sgiehl** [comment]
Seems there had been no tests for importing compressed files, so I didn't mention that didn't work anymore.
Will create a PR to fix that and add some tests 🙈
