### ISSUE TITLE
Importer / Matomo fails with MySQL error on rows with certain characters (Python 3.7, Matomo 4.0.5)

### ISSUE THREAD

**Issue by peterbo** [matomo-org/matomo-log-analytics#293]
The URL in the log is:

`/piwik/piwik.php?action_name=404&idsite=244&rec=1&r=668109&h=10&m=35&s=37&url=https%3A%2F%2Fwww.xxxxxx.com%2Ffilmhaus%2Fkino-3%E2%80%A8%E2%80%A8%3Ffbclid%3Dxxx&urlref=http%3A%2F%2Fm.facebook.com&_id=bef504b69xxx&_idn=1&_refts=1607020538&_ref=http%3A%2F%2Fm.facebook.com&send_image=0&cookie=1&res=375x812&pv_id=zOrnBt&pf_net=0&pf_srv=1447&pf_tfr=265&pf_dm1=1590 HTTP/1.1" 204 4024 "https://xxxxxxx.com/filmhaus/kino-3%E2%80%A8%E2%80%A8?fbclid=xxx"`

The importer fails with error 500. In the Error log, the following info is logged:
`AH01071: Got error 'PHP message: Error in Matomo (tracker): Error query: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\\xE2_\\xA8\\xE2_\\xA8' for column `xxxx`.`piwik_log_action`.`name` at row 1 In query: INSERT INTO piwik_log_action (name, hash, type, url_prefix) VALUES (?,CRC32(?),?,?) Parameters: array (   0 => 'xxxxxxxx.com/filmhaus/kino-3\xe2_\xa8\xe2_\xa8',   1 => 'xxxxxx.com/filmhaus/kino-3\xe2_\xa8\xe2_\xa8',   2 => 1,   3 => 3, )'`

**Comment by sgiehl** [comment]
Seems that is an encoded `⟨⟨` 🤔 
Are the database tables converted to utf8mb4?

**Comment by peterbo** [comment]
@sgiehl good point - they aren't yet converted! I'll convert and test again

**Comment by valerio-bozzolan** [comment]
Yup. Logs are usually full of crap but updating Matomo schema to `utf8mb4` allows you to import this kind of stuff without any issue.

As already said you can fix issuing this command:

```
./console core:convert-to-utf8mb4 
```

(Source: https://phabricator.wikimedia.org/T279228)

**Comment by sgiehl** [comment]
Closing this. @peterbo If you still have issues when importing special chars even when using utf8mb4, feel free to create a new issue.
