### ISSUE TITLE
Error query: Mysqli statement execute error : Out of range value for column ‘time_transfer’ at row 1 In query

### ISSUE THREAD

**Issue by whikloj** [matomo-org/matomo-log-analytics#306]
I keep seeing this error in my logs, the full message is

> Error in Matomo (tracker): Error query: Mysqli statement execute error : Out of range value for column ‘time_transfer’ at row 1 In query: INSERT INTO log_link_visit_action (idvisit, idsite, idvisitor, idaction_url, idaction_url_ref, idaction_name_ref, server_time, idpageview, pageview_position, time_spent_ref_action, time_network, time_server, time_transfer, idaction_name) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?) Parameters: array ( 0 => 45567, 1 =?$%’, 3 => 131240, 4 => 47630, 5 => 47629, 6 => ‘2021-01-24 18:56:18’, 7 => ‘lfC3a1’, 8 => 5, 9 => 913, 10 => 1214, 11 => 32, 12 => 1611073871470, 13 => 47629, )

I previously mentioned this in the [forums](https://forum.matomo.org/t/error-query-mysqli-statement-execute-error-out-of-range-value-for-column-time-transfer-at-row-1/40426) and it was suggested that this was similar to [this issue](https://github.com/matomo-org/matomo/issues/17035). That issue suggested opening an issue here, which I don't think was done (as I couldn't find one) so I am opening it now.

I'm running 4.1.0 (recently upgraded in case that has an impact).

**Comment by sgiehl** [comment]
Hi @whikloj 
Thanks for opening this issue. 
This is indeed similar to https://github.com/matomo-org/matomo/issues/17035 and also should be fixed once it was resolved.
As this problem occurs in Matomo core and actually not in log importing, I will simply close the issue here.
But we are aware of it, and it will be fixed in one of the next releases.

**Comment by sgiehl** [comment]
Sorry, just realized, this could possibly still be a problem in log analytics. Would you mind providing the parameters and log format you are using for importing logs? Maybe the detection for this value is broken in this case

**Comment by whikloj** [comment]
Hey @sgiehl , I realized after that this project is around log importing which is not what I'm doing. So I'll close this ticket and look to the core fix.
