### ISSUE TITLE
"--force-all-periods" option does not exist

### ISSUE THREAD

**Issue by chebourne** [matomo-org/matomo-log-analytics#307]
Since upgrading to Matomo 4.1.1 I am getting the following error after importing logs and issuing the aggregate creation script:

[RuntimeException]
The "--force-all-periods" option does not exist.

My current work flow is:
cd /var/www/html/piwik
sudo ./console core:archive --force-all-websites --force-all-periods=315576000 --force-date-last-n=1000 --url='https://*****/piwik'

Where ***** is my Piwik/Matomo URL.

Can anyone explain what has changed?

**Comment by Findus23** [comment]
Hi,

This sounds a bit like https://github.com/matomo-org/matomo/issues/16931 which should be solved with https://github.com/matomo-org/matomo-log-analytics/pull/296.

In short, you shouldn't need to run ` --force-all-periods=315576000 --force-date-last-n=1000` anymore

**Comment by chebourne** [comment]
Yep, can confirm that seems the be the case - all latest months (Feb) logs aggregated ok.
Many thanks
