### ISSUE TITLE
Log Analytics incompatible with WordPress plugin?

### ISSUE THREAD

**Issue by schaum194** [matomo-org/matomo-log-analytics#325]
Hi!
Can you confirm that import_logs.py is incompatible with the WordPress plugin version of Matomo?

**Comment by schaum194** [comment]
Could somebody please answer yes or no? It's a bit urgent.
I need to know if I have to migrate the plugin data to an on-premise instance before switching to Log Analytics, since there's no going back from on-premise to plugin afaik...

**Comment by tsteur** [comment]
@schaum194 this is the case indeed. That's because the API is disabled there and token_auth cannot be created. I'll mention this in https://matomo.org/faq/wordpress/what-are-the-differences-between-matomo-on-premise-and-matomo-for-wordpress/

**Comment by schaum194** [comment]
You already did! Thank you!
Good to know that no further option digging will save me.
