### ISSUE TITLE
What should a correct json nginx log be formmated like?? json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by Jieiku** [matomo-org/matomo-log-analytics#332]
```bash
tail -1 /var/tmp/nginx.tmp
```

returns:

```
 {"ip": "40.88.21.235","host": "www.example.com","path": "/","status": "200","referrer": "https://www.example.com/","user_agent": "Mozilla/5.0 (compatible; DuckDuckGo-Favicons-Bot/1.0; +http://duckduckgo.com)","length": 2597,"generation_time_milli": 0.000,"date": "2022-04-03T20:11:06-07:00"}
```
The above is exact copy paste from my logs, except I changed the domain to example.com

here is what happens when I pipe it to matomo.sh:

`tail -1 /var/tmp/nginx.tmp | /usr/local/bin/matomo.sh`

```
Traceback (most recent call last):
  File "/usr/local/bin/import_logs.py", line 1588, in _call_api
    return json.loads(res)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/import_logs.py", line 2686, in <module>
    resolver = config.get_resolver()
  File "/usr/local/bin/import_logs.py", line 1131, in get_resolver
    return StaticResolver(self.options.site_id)
  File "/usr/local/bin/import_logs.py", line 1663, in __init__
    site = matomo.call_api(
  File "/usr/local/bin/import_logs.py", line 1647, in call_api
    return self._call_wrapper(self._call_api, None, None, method, **kwargs)
  File "/usr/local/bin/import_logs.py", line 1599, in _call_wrapper
    response = func(*args, **kwargs)
  File "/usr/local/bin/import_logs.py", line 1590, in _call_api
    raise urllib.error.URLError('Matomo returned an invalid response: ' + res.decode("utf-8") )
AttributeError: 'str' object has no attribute 'decode'
```

I suspect my log is not quite formatted correctly. Could somebody paste what the json log should look like, maybe then I can adjust things and get this working.

Thank You for any help, I appreciate it.

**Comment by Jieiku** [comment]
Im guessing this is related: https://stackoverflow.com/questions/28583565/str-object-has-no-attribute-decode-python-3-error

**Comment by Jieiku** [comment]
made some progress.....

I looked into the error and the python import script... it appeared to have to do with the url paramater...

so i changed:  

`--url=matomo.example.com`

to:

`--url=https://matomo.example.com/`

I am no longer crashing, but still no import (still investigating):

```
0 lines parsed, 0 lines recorded, 0 records/sec (avg), 0 records/sec (current)
Parsing log (stdin)...

Logs import summary
-------------------

    0 requests imported successfully
    0 requests were downloads
    1 requests ignored:
        0 HTTP errors
        0 HTTP redirects
        1 invalid log lines
        0 filtered log lines
        0 requests did not match any known site
        0 requests did not match any --hostname
        0 requests done by bots, search engines...
        0 requests to static resources (css, js, images, ico, ttf...)
        0 requests to file downloads did not match any --download-extensions
```

## UPDATE: Everything is working now! YAY!

I am assuming the test import did not work because it was duplicate data that the direct pipe to the matomo.sh had already happened. I see the traffic in the matomo dashboard now, all 2 hits! MUAHAHA!

Sooo to summarize this issue was caused the URL, both ways of specifying the URL are listed on the readme, but apparently you need the full format, eg `https://matomo.example.com/` instead of `matomo.example.com`

**Comment by justinvelluppillai** [comment]
Hi @Jieiku I'm glad you got your issue sorted. Just to clarify where is the faulty documentation? I see this page looks correct: https://matomo.org/faq/general/how-do-i-run-the-log-file-importer-script-with-default-options/

**Comment by Jieiku** [comment]
@justinvelluppillai  search this page https://github.com/matomo-org/matomo-log-analytics/blob/4.x-dev/README.md

look for `url=`

just below the line that reads

# How to use this script?

**Comment by BeanBagKing** [comment]
I had this and solved it in basically the same way. I was using `--url=http://` changed it to the correct `--url=https://` and it worked or at least got past that error. I'm not sure if this is exactly a bug, but it should probably have some better error handling.
