### ISSUE TITLE
Matomo Log Analytics : config.ini.php could not be read.

### ISSUE THREAD

**Issue by ignace72** [matomo-org/matomo-log-analytics#347]
Good evening to all.
I'm trying to inject my server log into my Matomo installation on my GNU/Linux Nginx server.

I put the matomo-log-analytics files in `/opt/matomo/matomo-log-analytics/`.
My website is in `/var/www/html/.`
I have installed Matomo in` /var/www/html/matomo/` with the matomo subdomain.
When I run the following command:
`sudo python3 ./import_logs.py --url="matomo.xxxxxx.eu" /var/log/nginx/access.log`
I have the following error:
`Fatal error: the configuration file/opt/config/config.ini.php could not be read. Please check permission. This file must be readable by the user running this script to get the authentication token`
Or the script had the idea to look for a file in a place that does not exist?

Does anyone have any idea what the problem is and how to fix it?
Thanks to all.

**Comment by abhibeckert** [comment]
I had to add `--config path/to/config/config.ini.php`.

**Comment by ignace72** [comment]
Hello, abhibeckert.
Okay, I'll do that.
Thank you very much.

**Comment by ignace72** [comment]
Good evening.
I added the option (with also idsite) and it still doesn't work. 
Here is the message from the terminal:

```
Traceback (most recent call last):
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 1588, in _call_api
    return json.loads(res)
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 2688, in <module>
    resolver = config.get_resolver()
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 1131, in get_resolver
    return StaticResolver(self.options.site_id)
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 1663, in __init__
    site = matomo.call_api(
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 1647, in call_api
    return self._call_wrapper(self._call_api, None, None, method, **kwargs)
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 1599, in _call_wrapper
    response = func(*args, **kwargs)
  File "/opt/matomo/matomo-log-analytics/./import_logs.py", line 1590, in _call_api
    raise urllib.error.URLError('Matomo returned an invalid response: ' + res.decode("utf-8") )
AttributeError: 'str' object has no attribute 'decode'
```

If anyone has any idea what the problem is?
Thank you.

**Comment by marcbria** [comment]
Same issue with a dockerized matomo:4.14.1 and debian 11.

First issue is the config path that could be fixed with "-config" parameter.
Second issue when calling the script... probably because debian 11 is released with python3.9 and script requires 3.7 max?

**Comment by ignace72** [comment]
Hello, marcbria.
Uh, the script would not be compatible out of the box with one of the most used GNU/Linux distributions for WEB servers!
I think in dreaming.
Well, I'll see if I can install Python 3.7, I'll come back here to tell if it worked.
Thank you very much.

**Comment by marcbria** [comment]
I'm a community member... as lost with this as you. ;-)

The script comments talk about 3.5, 3.6 or 3.7 so I'm installing python3.7 right now but I just realize README talks about Python 3.5, 3.6, 3.7, 3.8, 3.9, 3.10.

PD: Tooo late in this side of the earth... I will continue tomorrow.

**Comment by ignace72** [comment]
I am not incriminating you in any way.
Far from me, this idea.
I can imagine that you are as surprised as I am.
It's very late here too, but as I sleep very little, I'm used to it.
Good night to you.

**Comment by marcbria** [comment]
No offense at all.
I installed python3.7 and the problem persisted. 

I think the error was more simple than this... I'm tying now with the matomo URL in the url (instead of the place I wanted to track that is referenced by the id param) and I also added a tokenauth.

Call is:
```
python3 import_logs.py --url=https://YourMatomoUrl --idsite=1 --recorders=8 --enable-http-errors --enable-http-redirects --enable-static --enable-bots /usr/local/apache2/logs/access.log --token-auth=YOURTOKEN
````

Looks like is working but I'm analyzing 4GB of logs so I can tell for sure... till tomorrow.

**Comment by ignace72** [comment]
Great, obviously you found it, I will test this when I am calmer.
Then I prefer to wait wisely to be sure that you are without surprise before the end of the treatment.
Obviously, 4GB is a lot.
I have smaller files, easier to read.

Edited:
Good, it processes the file (12 MiB).
But I have to search for adding my old access.log files to Matomo.
It's, well, the situation is progressing.

Edited:
I finished the first file, 21 more to go.
Some are a few megs, some are a hundred.
Well, I'll sleep better tonight.
Once I get going, I better not stop.

Edited:
I collected the access.log. files in a directory and ran the command with as access.log.* file which processes all the files in the directory and there is nothing to do but wait.

Eidted:
Thanks to you, abhibeckert and marcbria.
The problem being solved, I close the thread.

**Comment by ignace72** [comment]
Hello everyone.
Unfortunately, it crashes after 8 hours of treatment.
Here is the error:
2023-04-15 12:14:03,838: [INFO] Error when connecting to Matomo: HTTP Error 500: Internal Server Error
2023-04-15 12:14:03,839: [INFO] Max number of attempts reached, server is unreachable!
Fatal error: HTTP Error 500 Internal Server Error, response: {"status": "error", "tracked":1, "invalid":0, "invalid_indices":[]}
You can restart the import of "access-nginx/access.log" from the point it failed by specifying --skip=6418 on the command line.
