### ISSUE TITLE
Log Analytics: on IIS Error: Unauthorized 

### ISSUE THREAD

**Issue by mattab** [matomo-org/matomo-log-analytics#36]
There was a long thread in the forums where the reported issue is:

```
E:\Piwik\piwik\misc\log-analytics>python import_logs.py --url=http://arf E:\logf
iles2\Intranet\ARF_net_iis05\W3SVC769991110\ex140118.log
Fatal error: Unauthorized 
```

at least three users are discussing this issue. The solution is [in this post](https://forum.matomo.org/t/cant-import-iis-logs/11583) 

##### Solution to Unauthorized error

Enable Anonymous authentication in your IIS ... edit it and choose 'Application Pool' instead of a specific user. If this works then you can change the Anonymous authentication to the user of your choice.

PS. You can also enable anonymous authentication only to your piwik virtual directory.
##### Steps

Maybe we could detect this error and display the solution to user? or create a FAQ?

Migrated from piwik/piwik#6286

**Comment by sgiehl** [comment]
As there hadn't been any similar reports in last decade, we will close this issue as won't fix. If anyone still experiences this issue, please open a new issue. Thanks.
