### ISSUE TITLE
Broken documentation url in script header

### ISSUE THREAD

**Issue by kouinkouin** [matomo-org/matomo-log-analytics#370]
Hi,

In the header of `import_logs.py`, there is a link to access to documentation: https://matomo.org/docs/log-analytics-tool-how-to/ .
Is it possible to put a right URL? (I don't know what is the right page...)

https://github.com/matomo-org/matomo-log-analytics/blob/d1cd2fedf7ed9046a5109c366b44845739db86bc/import_logs.py#L11C60-L11C109:
> For more info see: https://matomo.org/log-analytics/ and https://matomo.org/docs/log-analytics-tool-how-to/

Thanks!

**Comment by michalkleiner** [comment]
Hi @kouinkouin, can you please let us know what is wrong with the current link or what other content would you expect to see? It goes to a landing page for all things about log importing. There's no specific documentation apart from the README here and that FAQ/guides area on matomo.org website.

**Comment by kouinkouin** [comment]
Hi @michalkleiner ,
Indeed, I expected to see the technical info about the log analytics tool.
The link redirects to the faq but not (anymore?) to the technical guide (options of the script).
The readme seems what I expected, sorry to do not see it before (and to open an issue before read it...) :-/ .
Maybe write the URL of the readme in the header of the script? I have what I searched, so you can close the issue if you want.

**Comment by michalkleiner** [comment]
Thanks for your reply @kouinkouin. I think for now we'll keep the link as is as it's pointing to a list of resources and articles that may help across wider area. I'll close the issue for now but if someone else comes across it as well and feels strongly about changing the links we can discuss that with the product owners.
